name: get_color
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  intl: ^0.17.0
  flutter_localization: ^0.1.11
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  bloc_concurrency: ^0.2.2

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/GC_splash.png
  image_dark: assets/images/GC_splash.png

  android_12:
    color: "#ffffff"
    color_dark: "#ffffff"
    image: assets/images/GC_splash.png
    image_dark: assets/images/GC_splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/GC_logo.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: "assets/icon/GC_logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf 
